### ISSUE TITLE
NullPointerException 발생할 수 있음, bonusArray 초기화 코드부터 작성 요청

### ISSUE THREAD

**Issue by startupcodekr** [100-hours-a-week/5-hailey-java-cli#4]
https://github.com/100-hours-a-week/5-hailey-java-cli/blob/851a4a826f3cafefdd9613651f0e55605bc43677/src/main/java/com/lotto/number/BonusLottoNumber.java#L19

**Comment by hhee3** [comment]
최상위 클래스 Number에서 bonusArray를 초기화하고 있는데 추가로 초기화 코드가 필요한가요 ?

**Comment by startupcodekr** [comment]
의도를 명확하게 보여주는게 좋죠. 사실 최상위 클래스 Number 클래스가 배열변수만 있기에 적절하진 않다고 생각해요.
