### ISSUE TITLE
보너스번호가 기존번호와 겹치지않는지 확인하는 코드가 필요해보입니다.

### ISSUE THREAD

**Issue by startupcodekr** [100-hours-a-week/5-hailey-java-cli#5]
https://github.com/100-hours-a-week/5-hailey-java-cli/blob/851a4a826f3cafefdd9613651f0e55605bc43677/src/main/java/com/lotto/number/BonusLottoNumber.java#L20

**Comment by hhee3** [comment]
시나리오상 보너스 번호는 특별번호로 단순히 1-45 중 아무거나 고르는 번호입니다! 그래서 기존 번호와 별도로 취급되어 보너스 번호만 맞춰도 포인트가 지급됩니다 
그래서 겹치는지 안겹치는지 확인하는 로직을 안넣었습니다
현실세계 로또와는 조금 다르지요 ㅎㅎ..

**Comment by startupcodekr** [comment]
아 넵 이해했습니다
